//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistsCanciones
    {
        public int idPlaylist { get; set; }
        public int idCancion { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual Canciones Canciones { get; set; }
        public virtual Playlists Playlists { get; set; }
    }
}
