//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Playlists = new HashSet<Playlists>();
            this.UsuariosActividades = new HashSet<UsuariosActividades>();
            this.UsuariosSentimientos = new HashSet<UsuariosSentimientos>();
        }
    
        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        public string A_Paterno { get; set; }
        public string A_Materno { get; set; }
        public string Correo { get; set; }
        public byte[] Clave { get; set; }
        public string Username { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int idPais { get; set; }
        public int idTipoUsuario { get; set; }
        public int idEstado { get; set; }
        public string Imagen { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Paises Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlists> Playlists { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosActividades> UsuariosActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosSentimientos> UsuariosSentimientos { get; set; }
    }
}
